# Generated by Django 4.0.5 on 2022-06-26 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cobro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipoInscripcion', models.CharField(max_length=50)),
                ('descripcion', models.CharField(max_length=50)),
                ('costo', models.PositiveIntegerField()),
                ('fechaCobro', models.DateField()),
            ],
        ),
    ]
