# Generated by Django 4.0.5 on 2022-06-27 16:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_ciudad'),
    ]

    operations = [
        migrations.CreateModel(
            name='FichaInscripcion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fechaInscripcion', models.CharField(max_length=50)),
                ('peso', models.CharField(max_length=20)),
                ('estatura', models.CharField(max_length=20)),
            ],
            options={
                'verbose_name': 'FichaInscripcion',
                'verbose_name_plural': 'FichaInscripcines',
                'db_table': 'fichaInscripcion',
            },
        ),
        migrations.AddField(
            model_name='ciudad',
            name='FichaInscripcion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.fichainscripcion'),
        ),
        migrations.AddField(
            model_name='cliente',
            name='FichaInscripcion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.fichainscripcion'),
        ),
        migrations.AddField(
            model_name='cobro',
            name='FichaInscripcion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.fichainscripcion'),
        ),
    ]
