# Generated by Django 4.0.5 on 2022-06-27 18:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_fichainscripcion_ciudad_fichainscripcion_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='fichainscripcion',
            options={},
        ),
        migrations.RemoveField(
            model_name='ciudad',
            name='FichaInscripcion',
        ),
        migrations.RemoveField(
            model_name='cliente',
            name='FichaInscripcion',
        ),
        migrations.RemoveField(
            model_name='cobro',
            name='FichaInscripcion',
        ),
        migrations.AlterModelTable(
            name='fichainscripcion',
            table=None,
        ),
    ]
