# Generated by Django 4.0.5 on 2022-06-27 18:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_fichainscripcion_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='fichainscripcion',
            name='ciudad',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.ciudad'),
        ),
        migrations.AddField(
            model_name='fichainscripcion',
            name='cliente',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.cliente'),
        ),
        migrations.AddField(
            model_name='fichainscripcion',
            name='cobro',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.cobro'),
        ),
    ]
