# Generated by Django 4.0.5 on 2022-06-28 18:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_alter_fichainscripcion_fechainscripcion'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pago',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('montoTotal', models.IntegerField()),
                ('mesPagado', models.CharField(max_length=20)),
                ('fechaPago', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='DetallePago',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('montoDetalle', models.IntegerField()),
                ('fechaDetalle', models.DateField()),
                ('descripcion', models.CharField(max_length=20)),
                ('inscripcion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.fichainscripcion')),
                ('pag', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.pago')),
            ],
        ),
        migrations.AddField(
            model_name='fichainscripcion',
            name='detallePago',
            field=models.ManyToManyField(through='api.DetallePago', to='api.pago'),
        ),
    ]
